#!/usr/bin/env bash

# Usage:
# ./solc [options] inputfile > outfile

# Notes:
# - file i/o is limited to the current directory
# - this works with the pyethereum solc_wrapper

#docker run -i --rm --user $(id -u):$(id -g) -v $(pwd):/metadium --workdir /metadium ethereum/solc:0.4.24 --solc-paths="../=/metadium/contracts/" $@
docker run -i --rm --user $(id -u):$(id -g) -v $(pwd):/metadium --workdir /metadium ethereum/solc:0.4.24 $@
